// <auto-generated />
using System;
using GuardiaoDasMemorias.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GuardiaoDasMemorias.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225030353_SeparaTabelasSchemaPagamentoParaPlanoOuContrato")]
    partial class SeparaTabelasSchemaPagamentoParaPlanoOuContrato
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Cliente.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("clientes", "cliente");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Contrato.ContratoHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("ContratoAntigoId")
                        .HasColumnType("integer")
                        .HasColumnName("contrato_antigo_id");

                    b.Property<int>("ContratoNovoId")
                        .HasColumnType("integer")
                        .HasColumnName("contrato_novo_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacao");

                    b.Property<DateTime>("RealizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("realizado_em");

                    b.Property<string>("TipoMudanca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_mudanca");

                    b.HasKey("Id");

                    b.HasIndex("ContratoAntigoId");

                    b.HasIndex("ContratoNovoId");

                    b.HasIndex("TipoMudanca", "RealizadoEm");

                    b.ToTable("contrato_historico", "contrato", t =>
                        {
                            t.HasCheckConstraint("CK_ContratoHistorico_DiferentesContratos", "contrato_antigo_id != contrato_novo_id");
                        });
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Contrato.ContratoMemoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CanceladoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelado_em");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<int>("ContratoOrigemId")
                        .HasColumnType("integer")
                        .HasColumnName("contrato_origem_id");

                    b.Property<int>("ContratoStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("contrato_status_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<int>("MemoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("memoria_id");

                    b.Property<DateTime?>("PagoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pago_em");

                    b.Property<int>("PlanoId")
                        .HasColumnType("integer")
                        .HasColumnName("plano_id");

                    b.Property<string>("TransacaoId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("transacao_id");

                    b.Property<decimal>("ValorPago")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_pago");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ContratoOrigemId");

                    b.HasIndex("MemoriaId");

                    b.HasIndex("PlanoId");

                    b.HasIndex("ContratoStatusId", "ExpiraEm");

                    b.ToTable("contrato_memoria", "contrato");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Contrato.ContratoOrigem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("contrato_origem", "contrato");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Compra no Site"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Afiliado"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Presente Admin"
                        });
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Contrato.ContratoStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("contrato_status", "contrato");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Pendente"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Ativo"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Cancelado"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Expirado"
                        });
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Memoria.Memorias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("MemoriaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("memoria_hash");

                    b.Property<int>("TemaId")
                        .HasColumnType("integer")
                        .HasColumnName("tema_id");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MemoriaHash")
                        .IsUnique();

                    b.HasIndex("TemaId");

                    b.HasIndex("TemplateId");

                    b.ToTable("memorias", "memoria");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Musica.Musicas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("caminho");

                    b.Property<int>("MemoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("memoria_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("MemoriaId");

                    b.ToTable("musicas", "musica");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Plano.PlanoLimites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<int>("PlanoId")
                        .HasColumnType("integer")
                        .HasColumnName("plano_id");

                    b.Property<string>("Propriedade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("propriedade");

                    b.Property<int>("Valor")
                        .HasColumnType("integer")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("PlanoId", "Propriedade")
                        .IsUnique();

                    b.ToTable("plano_limites", "plano");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Plano.PlanoRecursos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("PlanoId")
                        .HasColumnType("integer")
                        .HasColumnName("plano_id");

                    b.Property<string>("RecursoKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recurso_key");

                    b.HasKey("Id");

                    b.HasIndex("PlanoId", "RecursoKey")
                        .IsUnique();

                    b.HasIndex("PlanoId", "Ativo", "Ordem");

                    b.ToTable("plano_recursos", "plano");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Plano.Planos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("Atualizado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Criado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco");

                    b.Property<int>("TemaId")
                        .HasColumnType("integer")
                        .HasColumnName("tema_id");

                    b.Property<int>("TipoPagamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_pagamento_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("TipoPagamentoId");

                    b.HasIndex("TemaId", "Ativo");

                    b.ToTable("planos", "plano");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Plano.TipoPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("tipo_pagamento", "plano");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Pagamento Único"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Assinatura"
                        });
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Tema.Temas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("temas", "tema");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Template.Templates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("TemaId")
                        .HasColumnType("integer")
                        .HasColumnName("tema_id");

                    b.HasKey("Id");

                    b.HasIndex("TemaId");

                    b.ToTable("templates", "template");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", "auth");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Cliente.Clientes", b =>
                {
                    b.HasOne("GuardiaoDasMemorias.Models.ApplicationUser", "User")
                        .WithOne("Cliente")
                        .HasForeignKey("GuardiaoDasMemorias.Entities.Cliente.Clientes", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Contrato.ContratoHistorico", b =>
                {
                    b.HasOne("GuardiaoDasMemorias.Entities.Contrato.ContratoMemoria", "ContratoAntigo")
                        .WithMany("HistoricoComoAntigo")
                        .HasForeignKey("ContratoAntigoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GuardiaoDasMemorias.Entities.Contrato.ContratoMemoria", "ContratoNovo")
                        .WithMany("HistoricoComoNovo")
                        .HasForeignKey("ContratoNovoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContratoAntigo");

                    b.Navigation("ContratoNovo");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Contrato.ContratoMemoria", b =>
                {
                    b.HasOne("GuardiaoDasMemorias.Entities.Cliente.Clientes", "Cliente")
                        .WithMany("Contratos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GuardiaoDasMemorias.Entities.Contrato.ContratoOrigem", "ContratoOrigem")
                        .WithMany("ContratoMemorias")
                        .HasForeignKey("ContratoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GuardiaoDasMemorias.Entities.Contrato.ContratoStatus", "ContratoStatus")
                        .WithMany("ContratoMemorias")
                        .HasForeignKey("ContratoStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GuardiaoDasMemorias.Entities.Memoria.Memorias", "Memoria")
                        .WithMany("Contratos")
                        .HasForeignKey("MemoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GuardiaoDasMemorias.Entities.Plano.Planos", "Plano")
                        .WithMany("Contratos")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ContratoOrigem");

                    b.Navigation("ContratoStatus");

                    b.Navigation("Memoria");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Memoria.Memorias", b =>
                {
                    b.HasOne("GuardiaoDasMemorias.Entities.Cliente.Clientes", "Cliente")
                        .WithMany("Memorias")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GuardiaoDasMemorias.Entities.Tema.Temas", "Tema")
                        .WithMany("Memorias")
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GuardiaoDasMemorias.Entities.Template.Templates", "Template")
                        .WithMany("Memorias")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Tema");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Musica.Musicas", b =>
                {
                    b.HasOne("GuardiaoDasMemorias.Entities.Memoria.Memorias", "Memoria")
                        .WithMany("Musicas")
                        .HasForeignKey("MemoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Memoria");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Plano.PlanoLimites", b =>
                {
                    b.HasOne("GuardiaoDasMemorias.Entities.Plano.Planos", "Plano")
                        .WithMany("PlanoLimites")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Plano.PlanoRecursos", b =>
                {
                    b.HasOne("GuardiaoDasMemorias.Entities.Plano.Planos", "Plano")
                        .WithMany("PlanoRecursos")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Plano.Planos", b =>
                {
                    b.HasOne("GuardiaoDasMemorias.Entities.Tema.Temas", "Tema")
                        .WithMany("Planos")
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GuardiaoDasMemorias.Entities.Plano.TipoPagamento", "TipoPagamento")
                        .WithMany("Planos")
                        .HasForeignKey("TipoPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tema");

                    b.Navigation("TipoPagamento");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Template.Templates", b =>
                {
                    b.HasOne("GuardiaoDasMemorias.Entities.Tema.Temas", "Tema")
                        .WithMany("Templates")
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GuardiaoDasMemorias.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GuardiaoDasMemorias.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuardiaoDasMemorias.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GuardiaoDasMemorias.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Cliente.Clientes", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Memorias");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Contrato.ContratoMemoria", b =>
                {
                    b.Navigation("HistoricoComoAntigo");

                    b.Navigation("HistoricoComoNovo");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Contrato.ContratoOrigem", b =>
                {
                    b.Navigation("ContratoMemorias");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Contrato.ContratoStatus", b =>
                {
                    b.Navigation("ContratoMemorias");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Memoria.Memorias", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Musicas");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Plano.Planos", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("PlanoLimites");

                    b.Navigation("PlanoRecursos");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Plano.TipoPagamento", b =>
                {
                    b.Navigation("Planos");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Tema.Temas", b =>
                {
                    b.Navigation("Memorias");

                    b.Navigation("Planos");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Entities.Template.Templates", b =>
                {
                    b.Navigation("Memorias");
                });

            modelBuilder.Entity("GuardiaoDasMemorias.Models.ApplicationUser", b =>
                {
                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
